# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hack NTX
email: sponsor@techmill.co
description: >- # this means to ignore newlines until "baseurl:"
  Hack NTX is a civic technology hackathon focused on spurring civic engagement, utilizing open data, improving open government policies, and bolstering smart city innovations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hackntx.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:day/:title

# Social
twitter_username: techmilldenton
github_username:  techmilldenton
facebook_username:  techmilldenton
instagram_username:  techmilldenton
rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SASS
sass:
  sass_dir: ./_scss
  # style: compressed

# SEO
google_analytics: UA-51689839-6

author: techmilldenton
twitter:
  username: techmilldenton
  card: summary_large_image
logo: /assets/img/hackntx.png
social:
    name: TechMill Denton
    links:
      - https://twitter.com/techmilldenton
      - https://www.facebook.com/techmilldenton
      - https://www.linkedin.com/company/techmill-llc
      - https://github.com/techmilldenton

# Jekyll defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      image:
        path: assets/img/social/twitter-In-Stream_Wide___hackntx-social.jpg
        height: 640
        width: 1280
  - scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      category: "Default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
